export const categories = ["Love", "Grief", "Belief", "Joy", "Struggle"];

export const tags = [
  "Hope",
  "Sadness",
  "Sorrow",
  "Love",
  "Grief",
  "Belief",
  "Joy",
  "Struggle",
];

export const sampleQuestions = [
  "What makes life meaningful?",
  "How do you define happiness?",
  "What lesson did grief teach you?",
  "When did you last feel pure joy?",
  "How does belief shape your choices?",
  "What struggle made you stronger?",
  "Who taught you what love means?",
  "What brings you hope in hard times?",
  "When did you last feel truly at peace?",
  "What does success look like to you?",
  "How do you cope with failure?",
  "What part of your life would you change, if any?",
  "Who has influenced your worldview the most?",
  "What role does forgiveness play in your life?",
  "What’s something you’ve always wanted to learn but never have?",
  "What’s your idea of a perfect day?",
  "How do you find balance in life?",
  "What do you value most in friendships?",
  "How do you handle uncertainty?",
  "What’s one fear you’ve conquered?",
  "What is the best advice you’ve ever received?",
  "How do you stay motivated when things get tough?",
  "What does self-care look like for you?",
  "What memory makes you smile every time you think of it?",
  "How do you measure personal growth?",
  "What’s one thing you wish everyone knew about you?",
  "How has your definition of love evolved over time?",
  "What do you think is humanity’s greatest strength?",
  "When was the last time you did something for the first time?",
  "What do you consider your greatest accomplishment?",
  "What’s something small that always brightens your day?",
];
